version: "3.9"

services:
  ransomware-api:
    build: .
    container_name: ransomware-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - .:/app
